### ISSUE TITLE
Send Controller Improvements

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#262]
**Tasks** 

- [x] Apply new layout
- [x] Send Button should become active when there are no errors:
- when amount is valid (if invalid, display "Balance: xxx" in red)  @Dianaaiym 
- when address is valid (if invalid, display "Incorrect address") @Dianaaiym 
- [x] Exchange Rate
- (if available): all info shown(@TalgatNurdinov provide layout)
- (if not available): don't show rate, don't show base equivalent of fee, make switch inactive(@TalgatNurdinov provide layout)
-- unavailability of ex rate should not prevent user from sending transaction
- [ ] add Transaction Confirmation screen (@TalgatNurdinov provide layout). Make sure it shows destination address.

**Comment by TalgatNurdinov** [comment]
- [ ] Remove input border focus
<img width="1144" alt="screen shot 2018-11-13 at 12 21 27 pm" src="https://user-images.githubusercontent.com/42367908/48394678-b37b7000-e73e-11e8-874b-1db05284b920.png">

https://zpl.io/29ypO0e
https://zpl.io/VKlOPzA
https://zpl.io/VYR6Kgp

**Comment by TalgatNurdinov** [comment]
New Confirm layout 

<img width="248" alt="screen shot 2018-11-27 at 12 15 16 pm" src="https://user-images.githubusercontent.com/42367908/49062401-396ae100-f23e-11e8-8cf1-24d67c1dc762.png">

https://zpl.io/aMvOqoo

**Comment by TalgatNurdinov** [comment]
@Dianaaiym confirm, total

**Comment by rafaelekol** [comment]
Confirmation Dialog will be done with this ticket #285
