### ISSUE TITLE
IPFS Requests Optimizations

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-android#738]
At the moment there are some noticeable delays in getting data stored on IPFS. Upon further investigation of the issues it was agreed to apply following changes:

- [ ] (in progress by IPFS team) review whether there are any restrictions on IPFS Node in regards to the amount of requests/seconds a single client can make to the node. https://github.com/horizontalsystems/blockchain-meta/issues/49
- [x] apply new logic for retrieving relevant tx fees for the given blockchain, after the following issues is closed on IPFS team side https://github.com/horizontalsystems/blockchain-meta/issues/48
- [x] apply new logic for retrieving real-time exchanges rates https://github.com/horizontalsystems/blockchain-meta/issues/47
- [x] keep the ERC20 app icons stored locally, instead of getting them from IPFS.
- [x] make sure that after the user activates/adds new coins to the balance tab the client requests the rate data for the activated coins immediately after the coins added.
- [x] change the logic for how the historical rates are requested. On restore always ask for the rates of last 10 transactions, rather then last 10 for each coin. In total there should be no more than 10 requests. Consult with @ealymbaev about this, we have been running multiple tests with him
- [x] when user is on transactions tab, download rates only for those transactions that were seen on the screen. If user quickly scrolls through the list of transactions, they should not be downloaded. Only those where user has made a pause or scrolled slowly. That should significantly minimize the number of requests and make the client behave better.
